# cloudbuild.yaml
steps:
  # Step 1: Construct the image tag and write it to a file
  - name: 'bash'
    args:
      - '-c'
      - |
        echo "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_COMMIT_SHA}" > /workspace/image_tag.txt
    id: PrepareTag

  # Step 2: Build the container image using the tag from the file
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      # Read the tag from the file generated in the previous step
      - '--tag'
      - "$(cat /workspace/image_tag.txt)"
      # Pass build arguments to the Dockerfile, using provided substitutions
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}'
      - '--build-arg'
      # Use _PRODUCTION_URL substitution for both NEXT_PUBLIC_BASE_URL and PRODUCTION_URL build args
      - 'NEXT_PUBLIC_BASE_URL=${_PRODUCTION_URL}'
      - '--build-arg'
      - 'PRODUCTION_URL=${_PRODUCTION_URL}'
      # Specify the build context directory
      - '.'
    id: Build
    waitFor: [PrepareTag] # Wait for the tag file to be created

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID are automatically available
substitutions:
  _GCP_REGION: 'us-central1' 
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # Default, can be overridden if needed
  _COMMIT_SHA: '' # Must be passed in via --substitutions from workflow
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''
  # Must be passed in via --substitutions 