# cloudbuild.yaml

steps:
  # Step 1: Build the container image with ONLY a fixed temporary tag
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildImage
    args:
      - 'build'
      - '--tag'
      # Use a fixed, simple tag. DO NOT add Artifact Registry path here.
      - 'temp-image:latest'
      # Pass build arguments needed by the Dockerfile
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$_NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=$_PRODUCTION_URL'
      - '--build-arg'
      - 'PRODUCTION_URL=$_PRODUCTION_URL'
      # Specify the build context directory
      - '.'

  # Step 2: Tag and Push using docker commands within the docker builder environment
  # Using script + automap + USER-DEFINED SHA variable passed from workflow
  - name: 'gcr.io/cloud-builders/docker' # Changed back to docker builder
    id: TagAndPush
    # Make substitutions available as env vars
    automapSubstitutions: true 
    script: |
      #!/usr/bin/env bash
      # Exit script immediately on first error
      set -e
      
      # Define target image names using environment variables
      # Using _GITHUB_SHORT_SHA passed from the workflow
      TARGET_IMAGE_SHA="${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_GITHUB_SHORT_SHA}"
      TARGET_IMAGE_LATEST="${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest"
      
      # Log the variables to verify substitution
      echo "PROJECT_ID: ${PROJECT_ID}"
      echo "_GITHUB_SHORT_SHA: ${_GITHUB_SHORT_SHA}" # Check the user-defined SHA
      echo "_GCP_REGION: ${_GCP_REGION}"
      echo "_ARTIFACT_REGISTRY_REPOSITORY: ${_ARTIFACT_REGISTRY_REPOSITORY}"
      echo "_SERVICE_NAME: ${_SERVICE_NAME}"
      echo "Tagging image temp-image:latest as ${TARGET_IMAGE_SHA}"
      echo "Tagging image temp-image:latest as ${TARGET_IMAGE_LATEST}"

      # Use docker commands to tag
      docker tag temp-image:latest "${TARGET_IMAGE_SHA}"
      docker tag temp-image:latest "${TARGET_IMAGE_LATEST}"
      
      echo "Pushing ${TARGET_IMAGE_SHA}"
      docker push "${TARGET_IMAGE_SHA}"
      
      echo "Pushing ${TARGET_IMAGE_LATEST}"
      docker push "${TARGET_IMAGE_LATEST}"

    waitFor: [BuildImage]


# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID are automatically available ($SHORT_SHA seems broken)
substitutions:
  # Default, can be overridden if needed
  _GCP_REGION: 'us-central1'
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # User-defined SHA passed from workflow
  _GITHUB_SHORT_SHA: '' 
  # Must be passed in via --substitutions
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''

# Removed options block
# Removed _FULL_IMAGE_TAG substitution 