# cloudbuild.yaml
steps:
  # Build the container image using Docker via gcloud script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build \
          --tag "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA" \
          --build-arg "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}" \
          --build-arg "NEXT_PUBLIC_BASE_URL=${_PRODUCTION_URL}" \
          --build-arg "PRODUCTION_URL=${_PRODUCTION_URL}" \
          .
    id: Build

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID and COMMIT_SHA are automatically available
substitutions:
  _GCP_REGION: 'us-central1' 
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # Default, can be overridden if needed
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''
  # Must be passed in via --substitutions 