# cloudbuild.yaml
steps:
  # Build and push using the official Docker image builder
  - name: 'docker' # Use official docker image
    entrypoint: bash
    args:
      - '-c'
      - |
        # Construct the image tag
        IMAGE_TAG="${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_COMMIT_SHA}"
        echo "Using tag: $IMAGE_TAG"

        # Build the image
        docker build \
          --tag "$IMAGE_TAG" \
          --build-arg "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}" \
          --build-arg "NEXT_PUBLIC_BASE_URL=${_PRODUCTION_URL}" \
          --build-arg "PRODUCTION_URL=${_PRODUCTION_URL}" \
          .
        
        # Push the image explicitly
        docker push "$IMAGE_TAG"
    id: BuildAndPush

# No top-level images field needed as push is handled in the script

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID are automatically available
substitutions:
  _GCP_REGION: 'us-central1' 
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # Default, can be overridden if needed
  _COMMIT_SHA: '' # Must be passed in via --substitutions from workflow
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''
  # Must be passed in via --substitutions 