# cloudbuild.yaml

steps:
  # Step 1: Build the container image with a fixed temporary tag
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildImage
    args:
      - 'build'
      - '--tag'
      # Use a fixed, simple tag that doesn't require substitution here
      - 'temp-image:latest'
      # Pass build arguments needed by the Dockerfile
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$_NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=$_PRODUCTION_URL'
      - '--build-arg'
      - 'PRODUCTION_URL=$_PRODUCTION_URL'
      # Specify the build context directory
      - '.'

  # Step 2: Tag the built image with the $SHORT_SHA tag using docker tag via script
  - name: 'gcr.io/cloud-builders/docker'
    id: TagWithShortSHA
    # Make substitutions available as env vars
    automapSubstitutions: true 
    script: |
      #!/usr/bin/env bash
      set -e
      docker tag temp-image:latest "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
    waitFor: [BuildImage]

  # Step 3: Tag the built image with the 'latest' tag using docker tag via script
  - name: 'gcr.io/cloud-builders/docker'
    id: TagWithLatest
    # Make substitutions available as env vars
    automapSubstitutions: true 
    script: |
      #!/usr/bin/env bash
      set -e
      docker tag temp-image:latest "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest"
    waitFor: [BuildImage]

  # Step 4: Push the $SHORT_SHA tagged image via script
  - name: 'gcr.io/cloud-builders/docker'
    id: PushShortSHA
    # Make substitutions available as env vars
    automapSubstitutions: true 
    script: |
      #!/usr/bin/env bash
      set -e
      docker push "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
    # Wait for the specific tag step
    waitFor: [TagWithShortSHA] 

  # Step 5: Push the latest tagged image via script
  - name: 'gcr.io/cloud-builders/docker'
    id: PushLatest
    # Make substitutions available as env vars
    automapSubstitutions: true 
    script: |
      #!/usr/bin/env bash
      set -e
      docker push "${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest"
    # Wait for the specific tag step
    waitFor: [TagWithLatest] 


# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID, $SHORT_SHA are automatically available
substitutions:
  # Default, can be overridden if needed
  _GCP_REGION: 'us-central1'
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # _COMMIT_SHA removed - using built-in $SHORT_SHA instead
  # Must be passed in via --substitutions
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''

# Removed options block
# Removed _FULL_IMAGE_TAG substitution 