# cloudbuild.yaml

# Use the top-level 'images' field to automatically build and push ONLY the 'latest' tag.
# Dynamic tagging ($SHORT_SHA) will be done in the GitHub Actions workflow AFTER the build.
images:
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'

# Define expected substitution variables needed ONLY for build arguments
substitutions:
  # Built-in PROJECT_ID is automatically available
  # Defaults, can be overridden if needed
  _GCP_REGION: 'us-central1' 
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  _SERVICE_NAME: 'nwa-campaign-website'
  # SHA substitutions removed
  # Build arguments passed from workflow
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: '' 
  _PRODUCTION_URL: ''

# Pass build arguments to the Docker build process using options.buildArgs
# This should work with the simple 'images:' field above
options:
  logging: CLOUD_LOGGING_ONLY
  buildArgs:
    # Use the direct substitution syntax $_VAR here
    - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$_NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
    - 'NEXT_PUBLIC_BASE_URL=$_PRODUCTION_URL'
    - 'PRODUCTION_URL=$_PRODUCTION_URL' 