# cloudbuild.yaml
steps:
  # Build the container image using Docker via gcloud script
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Step 1: Construct the image tag and write it to a temporary variable (or file if preferred)
        IMAGE_TAG="${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_COMMIT_SHA}"
        echo "Using tag: $IMAGE_TAG"

        # Step 2: Build the image using the constructed tag
        docker build \
          --tag "$IMAGE_TAG" \
          --build-arg "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}" \
          --build-arg "NEXT_PUBLIC_BASE_URL=${_PRODUCTION_URL}" \
          --build-arg "PRODUCTION_URL=${_PRODUCTION_URL}" \
          .
    id: Build

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID are automatically available
substitutions:
  _GCP_REGION: 'us-central1' 
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # Default, can be overridden if needed
  _COMMIT_SHA: '' # Must be passed in via --substitutions from workflow
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''
  # Must be passed in via --substitutions 