# cloudbuild.yaml

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '--tag'
      # Tag with region, project, repo, service name - use $SHORT_SHA for commit hash
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      # Also tag with latest
      - '--tag'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'
      # Pass build arguments needed by the Dockerfile
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$_NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=$_PRODUCTION_URL'
      - '--build-arg'
      - 'PRODUCTION_URL=$_PRODUCTION_URL'
      # Specify the build context directory
      - '.'

  # Step 2: Push the image tagged with $SHORT_SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: PushShortSHA
    args:
      - 'push'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
    waitFor: [Build]

  # Step 3: Push the image tagged with latest
  - name: 'gcr.io/cloud-builders/docker'
    id: PushLatest
    args:
      - 'push'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'
    waitFor: [PushShortSHA] # Wait for the SHA push to complete

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID, $SHORT_SHA are automatically available
substitutions:
  # Default, can be overridden if needed
  _GCP_REGION: 'us-central1'
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # _COMMIT_SHA removed - using built-in $SHORT_SHA instead
  # Must be passed in via --substitutions
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''

# Removed options block - logging defaults to CLOUD_LOGGING_ONLY anyway
# Removed _FULL_IMAGE_TAG substitution 