# cloudbuild.yaml

steps:
  # Step 1: Build the container image with a fixed temporary tag
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '--tag'
      # Use a fixed, simple tag that doesn't require substitution here
      - 'image-to-tag:latest' 
      # Pass build arguments needed by the Dockerfile
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=$_NEXT_PUBLIC_STRIPE_PUBLIC_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_URL=$_PRODUCTION_URL'
      - '--build-arg'
      - 'PRODUCTION_URL=$_PRODUCTION_URL'
      # Specify the build context directory
      - '.'

  # Step 2a: Tag the image with $SHORT_SHA using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    id: TagWithShortSHA
    args:
      - 'artifacts'
      - 'docker'
      - 'tags'
      - 'add'
      - 'image-to-tag:latest' # Source image tag
      # Target image tag with $SHORT_SHA
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
    waitFor: [Build]

  # Step 2b: Tag the image with 'latest' using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    id: TagWithLatest
    args:
      - 'artifacts'
      - 'docker'
      - 'tags'
      - 'add'
      - 'image-to-tag:latest' # Source image tag
      # Target image tag with 'latest'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'
    waitFor: [Build]

  # Step 3: Push the images using gcloud artifacts command
  - name: 'gcr.io/cloud-builders/gcloud'
    id: PushWithGcloud
    args:
      - 'artifacts'
      - 'docker'
      - 'images'
      - 'push'
      # Push both tags
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'
    # Wait for both tags to be added before pushing
    waitFor: [TagWithShortSHA, TagWithLatest]


# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID, $SHORT_SHA are automatically available
substitutions:
  # Default, can be overridden if needed
  _GCP_REGION: 'us-central1'
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images' 
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website' 
  # _COMMIT_SHA removed - using built-in $SHORT_SHA instead
  # Must be passed in via --substitutions
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: '' 
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''

# Removed options block
# Removed _FULL_IMAGE_TAG substitution 