# cloudbuild.yaml

# Use the top-level 'images' field to automatically build, tag, and push.
# Cloud Build will substitute built-in variables like PROJECT_ID, _GCP_REGION, 
# _ARTIFACT_REGISTRY_REPOSITORY, _SERVICE_NAME, and $SHORT_SHA automatically.
images:
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
  # Also tag as 'latest' for easier reference
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:latest'

# Define steps only if needed for actions *other* than build/tag/push, 
# or if more complex build logic is required.
# In this case, we only need to pass build args, which can be done via options.

# Define expected substitution variables that can be passed via --substitutions
# Default substitutions like PROJECT_ID, $SHORT_SHA are automatically available
substitutions:
  # Default, can be overridden if needed
  _GCP_REGION: 'us-central1'
  # Default, can be overridden if needed
  _ARTIFACT_REGISTRY_REPOSITORY: 'nwa-campaign-images'
  # Default, can be overridden if needed
  _SERVICE_NAME: 'nwa-campaign-website'
  # _COMMIT_SHA removed - using built-in $SHORT_SHA instead
  # Must be passed in via --substitutions
  _NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ''
  # Must be passed in via --substitutions
  _PRODUCTION_URL: ''

# Pass build arguments to the Docker build process
options:
  logging: CLOUD_LOGGING_ONLY
  # Define substitutions for build arguments needed by Dockerfile
  # Note: These must match the keys in the 'substitutions' block above or be built-in substitutions.
  # Cloud Build automatically makes user-defined substitutions available as environment variables for the build-args
  # We just need to map them using build args. Format: --build-arg KEY=VALUE
  # For some reason Cloud Build sometimes needs explicit mapping even if names match.
  # Let's use the user-defined substitutions directly in the args definition.
  buildArgs:
    - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}'
    - 'NEXT_PUBLIC_BASE_URL=${_PRODUCTION_URL}'
    - 'PRODUCTION_URL=${_PRODUCTION_URL}'

# Removed _FULL_IMAGE_TAG substitution 